# Generated by Django 2.2 on 2019-04-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0002_auto_20190429_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationoftheday',
            options={'ordering': ('start_date', 'end_date'), 'verbose_name': 'Information du jour', 'verbose_name_plural': 'Informations of the day'},
        ),
        migrations.AddField(
            model_name='informationoftheday',
            name='title',
            field=models.CharField(default='default', max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
