# Generated by Django 2.2 on 2019-05-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0003_auto_20190429_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationoftheday',
            options={'ordering': ('start_date', 'end_date'), 'verbose_name': 'Information du jour', 'verbose_name_plural': 'Informations du jour'},
        ),
        migrations.AddField(
            model_name='period',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='period',
            name='max_child',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max child'),
        ),
        migrations.AddField(
            model_name='period',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='informationoftheday',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Titre'),
        ),
    ]
