# Generated by Django 2.2 on 2019-06-04 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0004_auto_20190531_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='allowed_login',
            field=models.ManyToManyField(related_name='classroom_login', to=settings.AUTH_USER_MODEL, verbose_name='Connexion autorisée'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nobinobi_child.Address', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Courriel'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Téléphone portable'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='professional_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Téléphone professionnel'),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='period',
            name='max_child',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max enfant'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Heure de début'),
        ),
    ]
