# Generated by Django 2.2 on 2019-06-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0005_auto_20190604_1406'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('first_name', 'last_name', 'phone')},
        ),
    ]
