# Generated by Django 2.2 on 2019-06-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0006_auto_20190604_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='usual_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom usuel'),
        ),
        migrations.AlterUniqueTogether(
            name='child',
            unique_together={('first_name', 'last_name', 'birth_date')},
        ),
    ]
