# Generated by Django 2.2 on 2019-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0007_auto_20190605_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom'),
        ),
    ]
