# Generated by Django 2.2 on 2019-07-11 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0008_language_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childtocontact',
            options={'ordering': ('order', 'child'), 'verbose_name': 'Enfant vers contact', 'verbose_name_plural': 'Enfants aux contacts'},
        ),
        migrations.AddField(
            model_name='agegroup',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agegroup',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='From date'),
            preserve_default=False,
        ),
    ]
