# Generated by Django 2.2 on 2019-10-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0009_auto_20190711_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='authorized_pick_up_child',
            field=models.NullBooleanField(verbose_name='Contact authorized to pick up the child.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='to_contact_if_needed',
            field=models.NullBooleanField(verbose_name='To contact if needed.'),
        ),
    ]
