# Generated by Django 2.2 on 2019-11-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0010_auto_20191016_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='type',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('day', 'Day')], default='morning', max_length=20, verbose_name='Type'),
        ),
    ]
