# Generated by Django 2.2 on 2019-11-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0011_auto_20191120_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='good_development',
            field=models.NullBooleanField(verbose_name='Good development'),
        ),
        migrations.AddField(
            model_name='child',
            name='health_insurance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Health Insurance'),
        ),
        migrations.AddField(
            model_name='child',
            name='healthy_child',
            field=models.NullBooleanField(verbose_name='Healthy child'),
        ),
        migrations.AddField(
            model_name='child',
            name='specific_problem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specific problem'),
        ),
        migrations.AddField(
            model_name='child',
            name='usage_paracetamol',
            field=models.NullBooleanField(verbose_name='Usage paracetamol'),
        ),
        migrations.AddField(
            model_name='child',
            name='vaccination',
            field=models.NullBooleanField(verbose_name='Vaccination'),
        ),
    ]
