# Generated by Django 2.2 on 2020-03-12 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import nobinobi_child.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ('nobinobi_child', '0012_auto_20191127_1157'),
    ]
    operations = [
        migrations.AddField(
            model_name='child',
            name='pediatrician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='pediatrician', to='nobinobi_child.Contact',
                                    verbose_name='Pediatrician'),
        ),
        migrations.AddField(
            model_name='child',
            name='pediatrician_contact',
            field=models.NullBooleanField(verbose_name='Pediatrician contact'),
        ),
    ]
