# Generated by Django 2.2 on 2020-03-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0013_add_pediatrician'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='sibling_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sibling birth date'),
        ),
        migrations.AddField(
            model_name='child',
            name='sibling_institution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Sibling's institution"),
        ),
        migrations.AddField(
            model_name='child',
            name='sibling_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Sibling's name and first name"),
        ),
    ]
