# Generated by Django 2.2 on 2020-03-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0014_add_sibling_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Child nationality'),
        ),
    ]
