# Generated by Django 2.2 on 2020-03-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0015_add_nationality_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='parental_authority',
            field=models.BooleanField(default=True, verbose_name='Parental authority'),
        ),
        migrations.AddField(
            model_name='contact',
            name='reside_with_child',
            field=models.BooleanField(default=True, verbose_name='Reside with child'),
        ),
    ]
