# Generated by Django 2.2 on 2020-03-19 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0016_add_information_contact_for_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='usage_homeopathy',
            field=models.NullBooleanField(verbose_name='Usage homeopathy'),
        ),
    ]
