# -*- coding: utf-8 -*-
import django.contrib.auth.views as auth_views
from django.conf.urls import url
from django.urls import path

from nobinobi_child.forms import LoginAuthenticationForm
from . import views

app_name = 'nobinobi_child'
urlpatterns = [
    path('accounts/login/', views.AuthLoginView.as_view(), name='login_view'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='nobinobi_child/pages/login/logout.html'),
         name='logout_view'),
    path("", views.HomeView.as_view(), name="home"),
    url(
        regex="^Child/~create/$",
        view=views.ChildCreateView.as_view(),
        name='Child_create',
    ),
    url(
        regex="^Child/(?P<pk>\d+)/~delete/$",
        view=views.ChildDeleteView.as_view(),
        name='Child_delete',
    ),
    url(
        regex="^Child/(?P<pk>\d+)/$",
        view=views.ChildDetailView.as_view(),
        name='Child_detail',
    ),
    url(
        regex="^Child/(?P<pk>\d+)/~update/$",
        view=views.ChildUpdateView.as_view(),
        name='Child_update',
    ),
    url(
        regex="^Child/$",
        view=views.ChildListView.as_view(),
        name='Child_list',
    ),
    url(
        regex="^Language/~create/$",
        view=views.LanguageCreateView.as_view(),
        name='Language_create',
    ),
    url(
        regex="^Language/(?P<pk>\d+)/~delete/$",
        view=views.LanguageDeleteView.as_view(),
        name='Language_delete',
    ),
    url(
        regex="^Language/(?P<pk>\d+)/$",
        view=views.LanguageDetailView.as_view(),
        name='Language_detail',
    ),
    url(
        regex="^Language/(?P<pk>\d+)/~update/$",
        view=views.LanguageUpdateView.as_view(),
        name='Language_update',
    ),
    url(
        regex="^Language/$",
        view=views.LanguageListView.as_view(),
        name='Language_list',
    ),
    url(
        regex="^Absence/~create/$",
        view=views.AbsenceCreateView.as_view(),
        name='Absence_create',
    ),
    url(
        regex="^Absence/(?P<pk>\d+)/~delete/$",
        view=views.AbsenceDeleteView.as_view(),
        name='Absence_delete',
    ),
    url(
        regex="^Absence/(?P<pk>\d+)/$",
        view=views.AbsenceDetailView.as_view(),
        name='Absence_detail',
    ),
    url(
        regex="^Absence/(?P<pk>\d+)/~update/$",
        view=views.AbsenceUpdateView.as_view(),
        name='Absence_update',
    ),
    url(
        regex="^Absence/$",
        view=views.AbsenceListView.as_view(),
        name='Absence_list',
    ),
    url(
        regex="^Classroom/~create/$",
        view=views.ClassroomCreateView.as_view(),
        name='Classroom_create',
    ),
    url(
        regex="^Classroom/(?P<pk>\d+)/~delete/$",
        view=views.ClassroomDeleteView.as_view(),
        name='Classroom_delete',
    ),
    url(
        regex="^Classroom/(?P<pk>\d+)/$",
        view=views.ClassroomDetailView.as_view(),
        name='Classroom_detail',
    ),
    url(
        regex="^Classroom/(?P<pk>\d+)/~update/$",
        view=views.ClassroomUpdateView.as_view(),
        name='Classroom_update',
    ),
    url(
        regex="^Classroom/$",
        view=views.ClassroomListView.as_view(),
        name='Classroom_list',
    ),
    url(
        regex="^AgeGroup/~create/$",
        view=views.AgeGroupCreateView.as_view(),
        name='AgeGroup_create',
    ),
    url(
        regex="^AgeGroup/(?P<pk>\d+)/~delete/$",
        view=views.AgeGroupDeleteView.as_view(),
        name='AgeGroup_delete',
    ),
    url(
        regex="^AgeGroup/(?P<pk>\d+)/$",
        view=views.AgeGroupDetailView.as_view(),
        name='AgeGroup_detail',
    ),
    url(
        regex="^AgeGroup/(?P<pk>\d+)/~update/$",
        view=views.AgeGroupUpdateView.as_view(),
        name='AgeGroup_update',
    ),
    url(
        regex="^AgeGroup/$",
        view=views.AgeGroupListView.as_view(),
        name='AgeGroup_list',
    ),
    url(
        regex="^AbsenceType/~create/$",
        view=views.AbsenceTypeCreateView.as_view(),
        name='AbsenceType_create',
    ),
    url(
        regex="^AbsenceType/(?P<pk>\d+)/~delete/$",
        view=views.AbsenceTypeDeleteView.as_view(),
        name='AbsenceType_delete',
    ),
    url(
        regex="^AbsenceType/(?P<pk>\d+)/$",
        view=views.AbsenceTypeDetailView.as_view(),
        name='AbsenceType_detail',
    ),
    url(
        regex="^AbsenceType/(?P<pk>\d+)/~update/$",
        view=views.AbsenceTypeUpdateView.as_view(),
        name='AbsenceType_update',
    ),
    url(
        regex="^AbsenceType/$",
        view=views.AbsenceTypeListView.as_view(),
        name='AbsenceType_list',
    ),
    url(
        regex="^AbsenceGroup/~create/$",
        view=views.AbsenceGroupCreateView.as_view(),
        name='AbsenceGroup_create',
    ),
    url(
        regex="^AbsenceGroup/(?P<pk>\d+)/~delete/$",
        view=views.AbsenceGroupDeleteView.as_view(),
        name='AbsenceGroup_delete',
    ),
    url(
        regex="^AbsenceGroup/(?P<pk>\d+)/$",
        view=views.AbsenceGroupDetailView.as_view(),
        name='AbsenceGroup_detail',
    ),
    url(
        regex="^AbsenceGroup/(?P<pk>\d+)/~update/$",
        view=views.AbsenceGroupUpdateView.as_view(),
        name='AbsenceGroup_update',
    ),
    url(
        regex="^AbsenceGroup/$",
        view=views.AbsenceGroupListView.as_view(),
        name='AbsenceGroup_list',
    ),
    url(
        regex="^ClassroomDayOff/~create/$",
        view=views.ClassroomDayOffCreateView.as_view(),
        name='ClassroomDayOff_create',
    ),
    url(
        regex="^ClassroomDayOff/(?P<pk>\d+)/~delete/$",
        view=views.ClassroomDayOffDeleteView.as_view(),
        name='ClassroomDayOff_delete',
    ),
    url(
        regex="^ClassroomDayOff/(?P<pk>\d+)/$",
        view=views.ClassroomDayOffDetailView.as_view(),
        name='ClassroomDayOff_detail',
    ),
    url(
        regex="^ClassroomDayOff/(?P<pk>\d+)/~update/$",
        view=views.ClassroomDayOffUpdateView.as_view(),
        name='ClassroomDayOff_update',
    ),
    url(
        regex="^ClassroomDayOff/$",
        view=views.ClassroomDayOffListView.as_view(),
        name='ClassroomDayOff_list',
    ),
    url(
        regex="^ChildToPeriod/~create/$",
        view=views.ChildToPeriodCreateView.as_view(),
        name='ChildToPeriod_create',
    ),
    url(
        regex="^ChildToPeriod/(?P<pk>\d+)/~delete/$",
        view=views.ChildToPeriodDeleteView.as_view(),
        name='ChildToPeriod_delete',
    ),
    url(
        regex="^ChildToPeriod/(?P<pk>\d+)/$",
        view=views.ChildToPeriodDetailView.as_view(),
        name='ChildToPeriod_detail',
    ),
    url(
        regex="^ChildToPeriod/(?P<pk>\d+)/~update/$",
        view=views.ChildToPeriodUpdateView.as_view(),
        name='ChildToPeriod_update',
    ),
    url(
        regex="^ChildToPeriod/$",
        view=views.ChildToPeriodListView.as_view(),
        name='ChildToPeriod_list',
    ),
    url(
        regex="^Period/~create/$",
        view=views.PeriodCreateView.as_view(),
        name='Period_create',
    ),
    url(
        regex="^Period/(?P<pk>\d+)/~delete/$",
        view=views.PeriodDeleteView.as_view(),
        name='Period_delete',
    ),
    url(
        regex="^Period/(?P<pk>\d+)/$",
        view=views.PeriodDetailView.as_view(),
        name='Period_detail',
    ),
    url(
        regex="^Period/(?P<pk>\d+)/~update/$",
        view=views.PeriodUpdateView.as_view(),
        name='Period_update',
    ),
    url(
        regex="^Period/$",
        view=views.PeriodListView.as_view(),
        name='Period_list',
    ),
    url(
        regex="^InformationOfTheDay/~create/$",
        view=views.InformationOfTheDayCreateView.as_view(),
        name='InformationOfTheDay_create',
    ),
    url(
        regex="^InformationOfTheDay/(?P<pk>\d+)/~delete/$",
        view=views.InformationOfTheDayDeleteView.as_view(),
        name='InformationOfTheDay_delete',
    ),
    url(
        regex="^InformationOfTheDay/(?P<pk>\d+)/$",
        view=views.InformationOfTheDayDetailView.as_view(),
        name='InformationOfTheDay_detail',
    ),
    url(
        regex="^InformationOfTheDay/(?P<pk>\d+)/~update/$",
        view=views.InformationOfTheDayUpdateView.as_view(),
        name='InformationOfTheDay_update',
    ),
    url(
        regex="^InformationOfTheDay/$",
        view=views.InformationOfTheDayListView.as_view(),
        name='InformationOfTheDay_list',
    ),
    url(
        regex="^Allergy/~create/$",
        view=views.AllergyCreateView.as_view(),
        name='Allergy_create',
    ),
    url(
        regex="^Allergy/(?P<pk>\d+)/~delete/$",
        view=views.AllergyDeleteView.as_view(),
        name='Allergy_delete',
    ),
    url(
        regex="^Allergy/(?P<pk>\d+)/$",
        view=views.AllergyDetailView.as_view(),
        name='Allergy_detail',
    ),
    url(
        regex="^Allergy/(?P<pk>\d+)/~update/$",
        view=views.AllergyUpdateView.as_view(),
        name='Allergy_update',
    ),
    url(
        regex="^Allergy/$",
        view=views.AllergyListView.as_view(),
        name='Allergy_list',
    ),
    url(
        regex="^ChildToContact/~create/$",
        view=views.ChildToContactCreateView.as_view(),
        name='ChildToContact_create',
    ),
    url(
        regex="^ChildToContact/(?P<pk>\d+)/~delete/$",
        view=views.ChildToContactDeleteView.as_view(),
        name='ChildToContact_delete',
    ),
    url(
        regex="^ChildToContact/(?P<pk>\d+)/$",
        view=views.ChildToContactDetailView.as_view(),
        name='ChildToContact_detail',
    ),
    url(
        regex="^ChildToContact/(?P<pk>\d+)/~update/$",
        view=views.ChildToContactUpdateView.as_view(),
        name='ChildToContact_update',
    ),
    url(
        regex="^ChildToContact/$",
        view=views.ChildToContactListView.as_view(),
        name='ChildToContact_list',
    ),
    url(
        regex="^Contact/~create/$",
        view=views.ContactCreateView.as_view(),
        name='Contact_create',
    ),
    url(
        regex="^Contact/(?P<pk>\d+)/~delete/$",
        view=views.ContactDeleteView.as_view(),
        name='Contact_delete',
    ),
    url(
        regex="^Contact/(?P<pk>\d+)/$",
        view=views.ContactDetailView.as_view(),
        name='Contact_detail',
    ),
    url(
        regex="^Contact/(?P<pk>\d+)/~update/$",
        view=views.ContactUpdateView.as_view(),
        name='Contact_update',
    ),
    url(
        regex="^Contact/$",
        view=views.ContactListView.as_view(),
        name='Contact_list',
    ),
    url(
        regex="^Address/~create/$",
        view=views.AddressCreateView.as_view(),
        name='Address_create',
    ),
    url(
        regex="^Address/(?P<pk>\d+)/~delete/$",
        view=views.AddressDeleteView.as_view(),
        name='Address_delete',
    ),
    url(
        regex="^Address/(?P<pk>\d+)/$",
        view=views.AddressDetailView.as_view(),
        name='Address_detail',
    ),
    url(
        regex="^Address/(?P<pk>\d+)/~update/$",
        view=views.AddressUpdateView.as_view(),
        name='Address_update',
    ),
    url(
        regex="^Address/$",
        view=views.AddressListView.as_view(),
        name='Address_list',
    ),
    url(
        regex="^FoodRestriction/~create/$",
        view=views.FoodRestrictionCreateView.as_view(),
        name='FoodRestriction_create',
    ),
    url(
        regex="^FoodRestriction/(?P<pk>\d+)/~delete/$",
        view=views.FoodRestrictionDeleteView.as_view(),
        name='FoodRestriction_delete',
    ),
    url(
        regex="^FoodRestriction/(?P<pk>\d+)/$",
        view=views.FoodRestrictionDetailView.as_view(),
        name='FoodRestriction_detail',
    ),
    url(
        regex="^FoodRestriction/(?P<pk>\d+)/~update/$",
        view=views.FoodRestrictionUpdateView.as_view(),
        name='FoodRestriction_update',
    ),
    url(
        regex="^FoodRestriction/$",
        view=views.FoodRestrictionListView.as_view(),
        name='FoodRestriction_list',
    ),
    url(
        regex="^ChildSpecificNeed/~create/$",
        view=views.ChildSpecificNeedCreateView.as_view(),
        name='ChildSpecificNeed_create',
    ),
    url(
        regex="^ChildSpecificNeed/(?P<pk>\d+)/~delete/$",
        view=views.ChildSpecificNeedDeleteView.as_view(),
        name='ChildSpecificNeed_delete',
    ),
    url(
        regex="^ChildSpecificNeed/(?P<pk>\d+)/$",
        view=views.ChildSpecificNeedDetailView.as_view(),
        name='ChildSpecificNeed_detail',
    ),
    url(
        regex="^ChildSpecificNeed/(?P<pk>\d+)/~update/$",
        view=views.ChildSpecificNeedUpdateView.as_view(),
        name='ChildSpecificNeed_update',
    ),
    url(
        regex="^ChildSpecificNeed/$",
        view=views.ChildSpecificNeedListView.as_view(),
        name='ChildSpecificNeed_list',
    ),
]
